### ISSUE TITLE
Start Page

### ISSUE THREAD

**Issue by Inelukas** [Inelukas/pet-app#16]
## Value proposition

As a Pet App user,
I want to access a Start Page,
that gives me a first impression of the game's atmosphere.

## Description
<will be added later>

## Acceptance criteria
- [ ]  Button behavior: Tapping on the "Start" button should initiate the game without delays.

## Tasks
- [ ]  Design the Start Page with a focus on the "Start" button
- [ ]   Implement the Start Page and ensure the "Start" button triggers the game.
