### ISSUE TITLE
Pet Details

### ISSUE THREAD

**Issue by Inelukas** [Inelukas/pet-app#3]
## Value proposition

As a user

I want to access detailed information about each virtual pet,
so that I can effectively monitor and manage the well-being of my pets.

## Description

![Image](https://github.com/user-attachments/assets/07280ba2-f1b7-4981-aae0-42c4938736ce)

## Acceptance criteria
- [x] Each pet in the pet list has a link to a details page.
- [x] Each details page contains:
   - [x] Pet name
   - [x] Pet emoji
   - [x] Pet characteristics 
- [x] Pet needs indicators, including health, happiness, hunger, intelligence and energy levels.
- [x] The pet needs indicators are displayed as a stats bar or numerical value.
- [x] The detailed view includes a “list” link, allowing users to easily navigate back to the list of pets.

## Tasks
- [x] Create feature branch feature/pet-details
- [x] create a "Details" Component
   - [x] create a "Indicator" component
   - [x] basic details + indicators
   - [x] implement back Link functionality (button design)
- [x] add Link element to Pet component

**Comment by ahohnsen** [comment]
Hi there!

Please adjust your **Acceptance Criteria**: The link to the "garden" is not part of this user story anymore. 🙂
