### ISSUE TITLE
App Design Overhaul

### ISSUE THREAD

**Issue by Inelukas** [Inelukas/pet-app#39]
## Value proposition

As a user,
I want to experience a visually appealing, user-friendly game interface,
In order to enjoy a smoother and more intuitive interaction with my pets and their environment.

## Description
The app will undergo a design overhaul, making design improvements across all pages. This will provide a more cohesive look and feel.

## Acceptance criteria
- [ ] The garden background resizes properly to fit a vertical layout.
- [ ] When there is only one pet, the next/previous buttons are disabled.
- [ ] All buttons have centered icons.
- [ ] The "dead pet" icon has been updated to a more appropriate design.
- [ ] The pet change bar on the garden page is redesigned for better UX/UI.
- [ ] Design updates are applied to all pages (list, details, create, garden).
- [ ] The app uses the final color palette for a consistent look.

## Tasks
- [ ] Resize the garden background to fit a vertical layout.
- [ ] Implement logic to disable next/previous buttons if only one pet exists.
- [ ] Center all button icons.
- [ ] Update the "dead pet" icon.
- [ ] Redesign the pet change bar on the garden page.
- [ ] Apply design updates to list, details, create, and garden pages.
- [ ] Implement the final color palette across all components and pages.
- [ ] Edit logo size on start page so that all elements fit on the screen.
- [ ] the current pet should be highlighted in the list view.

**Comment by F-Kirchhoff** [comment]
Hey,
looks good to me, good amount of detail about the different tasks.
