### ISSUE TITLE
Create Pet

### ISSUE THREAD

**Issue by Inelukas** [Inelukas/pet-app#4]
## Value proposition

As a user
I want to create and store new virtual pets,
so that I can keep track of my pet collection and enhance my pet care experience.

## Description

![Image](https://github.com/user-attachments/assets/aa8aa172-dbad-45c3-8d2a-f44a2bc76657)

## Acceptance criteria
- [ ] A form for adding virtual pets is displayed at the top of the homepage.
- [ ] The form is headlined with its purpose.
- [ ] The form must include labelled fields for:
   - [ ] Pet type
   - [ ] Pet name
- [ ] Pet characteristics
   - [ ] dropdown menu
   - [ ] up to two choices (at least one)
- [ ] Under the form is a section with the following content (displayed as bars):
   - [ ] Initial happiness level
   - [ ] Initial intelligence level
   - [ ] Initial energy level
- [ ] The following fields are mandatory:
   - [ ] Pet name
   - [ ] Pet emoji
   - [ ] Pet type
   - [ ] Pet characteristics
- [ ] The pet emoji is selected from the existing pet emoji list via arrow buttons.
- [ ] The pet type is automatically chosen upon chosing an emoji.
- [ ] The pet characteristics dropdown menu must include a default option, "Please select a characteristic", and require a selection.
- [ ] The initial happiness, energy, and intelligence levels change depending on the chosen characteristics. Health and energy are constant and thus not shown on the create screen.
- [ ] Form submission with any empty mandatory fields is blocked, and clear validation messages indicate the fields that need completion.
- [ ] Upon form submission, the new pet is added to the top of the pet list.

## Tasks
- [ ] Create feature branch feature/create-pet
- [ ] create "Pet Selection" component
   - [ ] "back" and "next" buttons
   - [ ] image
- [ ] create "Form" component
   - [ ] required data: name, personality
      - [ ] personality dropdown menu
   - [ ] not editable data: type
- [ ] render Indicator components
- [ ] - render "Cancel" button and dynamic "Create" button
- [ ] implement "currentPet" state

**Comment by ahohnsen** [comment]
Hi there!

Please update your Acceptance Criteria:

>  The pet type and pet emoji dropdowns must include a default option, "Please select a pet type/emoji", and require a selection.

You actually should not have a dropdown menu for the pet type anymore. If I understood correctly, the type is changing automatically when a pet emoji is chosen.

>  The initial happiness, energy, and intelligence levels change depending on the chosen characteristics. The health start value is constant.

What is with the initial hunger level? You do not mention it here anymore.

Additionally, your wireframe does not match your Acceptance Criteria. Please update it accordingly.
