### ISSUE TITLE
Pet Animations

### ISSUE THREAD

**Issue by Inelukas** [Inelukas/pet-app#44]
## Value proposition

As a user
I want to see different animations for my pets
In order to make the pets feel more alive and interactive during gameplay

## Description
We want to implement animations for pets in the game to increase engagement and make the pets appear more lifelike. Each pet will have three animations.
Example of a pet's sprite sheet (not all sprites will be used):

![Bildschirmfoto 2024-09-09 um 12 13 54](https://github.com/user-attachments/assets/7d7c7490-7a2e-49ed-a386-0e69c47de148)

![image](https://github.com/user-attachments/assets/ee3b652d-fc94-4016-9f61-daef8f0de81f)

## Acceptance criteria
- [ ] Animations 1 and 2 should trigger randomly within a set range of intervals (e.g., every 10–30 seconds).
- [ ] A death animation should trigger once when the pet’s health reaches zero and should not loop after it has finished.
- [ ] Animations must be smooth and visible across different screen sizes and resolutions.
- [ ] Ensure that the random animations do not overlap with the death animation.

## Tasks
- [ ] Implement the animations using sprite sheets (png) and CSS keyframes.
- [ ] Implement logic for triggering random animations at set intervals.
- [ ] Implement condition for triggering death animation when pet health reaches zero.
- [ ] Test the randomization of animations and ensure the death animation plays only once.

**Comment by eneben** [comment]
Hello team,
we have some suggestions to your user story. 
1) There is no wireframe. How does the developer know, where to implement the animation?
2) The description sounds more like the Acceptance Criteria. You almost write the same content in both sections.
3) The animation frames are very small and difficult to see.
4) In the tasks you have to write, what a developer has to know to be able to implement the user story. To repeat that there have to be three animations is not necessary, you write it in the AC. But you have to explain how to do this, p.ex. 
 - the developer does not know which format the animation has (a gif, different images, animation in css..)? 
 - how often should the animation be played?
 - ...

We are curious to see the final result. Your app looks already cute. 😊 👋

**Comment by Inelukas** [comment]
thanks for the review! 😊 I made some changes to the user story.
