### ISSUE TITLE
Graveyard

### ISSUE THREAD

**Issue by JohannMerck** [Inelukas/pet-app#45]
## Value proposition

As a user,
I want to visit a graveyard page where I can view my deceased pets,
so that I can keep track of pets I’ve lost and revive them.

## Description
A Graveyard Page is implemented that allows the user to view all deceased pets as well as revive them. The pets are displayed in a list, showing their names, an image, characteristics, time and date of death and type. The Graveyard can be visited via a link on the pet list page. The pets can be revived here. Revived pets come back to life as monsters/zombies with impaired features displayed in the pet list. 

![Image](https://github.com/user-attachments/assets/2696a236-d566-45a1-a81e-7b2567f41af5)

## Acceptance criteria

- [ ] a seperate graveyard page is implemented that can be accessed via a link on the pet list page.
- [ ] on the graveyard page a list of all deceased pets is displayed
- [ ] the list consists of containers for each deceased pet, displaying their names, characteristics, and type as well as an image of the dead pet and the date and time of death. 
- [ ] the pets can be revived on the graveyard page. reviving them causes the pet to reappear on the pet list page as a ghost with reduced features, i. e. revived pets can not be fed, etc. 
- [ ] reduced features mean all values of the pet (hunger, happiness, etc.) are constantly at zero and can not be increased by playing the mini-games anymore. the mini games are not available anymore. the buttons to the mini games are hidden.
- [ ] revived pets will still be selectable from the pet list though and therefore displayed in the garden. 
- [ ] a revived pet cannot die a second time. revived pets can only be deleted on the pet list -> pet details page. 
- [ ] It will still be possible to earn specific achievements with the revived pet, which will we implemented in the achievement user story.

## Tasks

- [ ] create gaveyard feature branch
- [ ] create graveyard page
- [ ] implement list for all deceased pets
- [ ] implement time and date of death of pet function
- [ ] implement functionality that displays revived pets as monsters on the pet list. 
- [ ] create link on pet list page to the graveyard page
- [ ] implement revive function 
- [ ] implement back to pet list link

**Comment by ahohnsen** [comment]
Heyho!

Please revise your **Value Proposition**. The second line should focus on what the user wants to do (an action), and the third line should clearly state the benefit. In your example, the user wants to see all deceased pets so they can potentially revive them. It could be written like this:

_As a user,
I want to visit a graveyard page where I can view my deceased pets,
so that I can keep track of pets I’ve lost and revive them._

Additionally, in the Acceptance Criteria, you mention that the pets come back as monsters with _reduced features_. Please list exactly which features will no longer be available or will change compared to a living pet. When writing a user story, keep in mind that it should be detailed enough for other developers to implement it in the way you expect.

I also suggest adding to the Acceptance Criteria how the differences will be reflected on the Garden Page. Will unavailable features be greyed out, or will they no longer be visible?
What happens when the monsters/zombies die? Can I revive them again, or is it only possible to revive them once?

**Comment by ahohnsen** [comment]
I have a question regarding your update:

Why should I want to revive a pet if I cannot interact with it at all? 🤔 I do not see the benefit of that feature...

**Comment by JohannMerck** [comment]
in general we wanted to implement a feature enabling the user to "keep the memory" of the pet alive. In addition, if it was possible to interact with the pet even after it dies, letting it die would not really have any negative consequences. finally it will still be possible to complete specific achievements with a revived pet.

**Comment by ahohnsen** [comment]
Please include in the Acceptance Criteria of this user story that while interactions with the pet are no longer possible, achievements can still be completed. It might also be helpful to specify exactly which achievements can still be earned after the pet’s death.

**Comment by JohannMerck** [comment]
alright, done - thank you :)
