### ISSUE TITLE
Tapping Game Improvement

### ISSUE THREAD

**Issue by JohannMerck** [Inelukas/pet-app#46]
## Value proposition

As a user i want to be able to access improved functionality within the tapping game,
In order to have a more enjoyable and more appealing playing experience. 

## Description

The tapping game will be further improved by debugging it and overall improvement of the functionality of the game. 

## Acceptance criteria

- [ ] Remove bug that causes the game to sometimes activate two backgrounds on one circle, i.e. lighting up one circle twice at the same time 
- [ ] adjust timer that prevents user from being able to gain multiple points by tapping one circle multiple times to only apply to one circle. At the moment, after tapping one circle the user is unable to gain points by tapping any other circle for 300ms. This feature is supposed to only occur for the last tapped circle, not every other circle as well. 
- [ ] Implement message displaying the score reached at the end of the 60s timer. 
- [ ] implement a third background (i.e. a third type of lighting up, but which appears fairly rarely) displaying a "treat" such as a bone or different types of animal food, rewarding the user with extra points
- [ ] implement responsive styling and overall improved styling

## Tasks

- [ ] create tapping-overhaul feature branch.
- [ ] debug lighting of one circle twice at the same time
- [ ] debug 300ms timer preventing the user from gaining multiple points by tapping multiple circles within one interval.
- [ ] adjust "time us up" - message by enhancing the duration and implementing display of final score obtained.
- [ ] implement display of a third changed background ("lighting up") of the circles, showing an animal treat rewarding extra points. 
- [ ] improve overall styling, primarily ensure responsiveness across all devices by implementing media querys (min-width 600px, 900px and 1200px).
