### ISSUE TITLE
Delete Pet

### ISSUE THREAD

**Issue by mexxlon** [Inelukas/pet-app#5]
## Value proposition

As a user

I want to be able to delete pets that are no longer relevant,

so that I can maintain a clean and organised pet list, ensuring it’s always up to date.

## Description

![Image](https://github.com/user-attachments/assets/f7ee7e40-91cf-404b-89d6-4fe46ca00232)

## Acceptance criteria
- [ ] Each pet details view includes an easily accessible delete option.
- [ ] Clicking the delete option triggers a confirmation dialog.
- [ ] The dialog serves to prevent accidental deletions by asking the user to confirm their intention.
- [ ] The dialog includes options for both confirming the deletion and cancelling the action.
- [ ] The cancellation option allows the user to back out of the deletion process if selected by mistake or if they 
change their mind.
- [ ] Upon confirming the deletion, the user is immediately redirected to the overview of all pets, and the pet is removed from the list.
- [ ] If all pets are deleted, a message appears indicating that there are no pets and providing an option to add new ones.

## Tasks
- [ ] feature branch delete-functionality
- [ ] implement delete button (pet detail component - next to pet picture)
- [ ] delete confirmation component 
   - [ ] confirmation dialogue - yes / cancel
- [ ] Delete and cancel button toggle delete state
- [ ] delete confirm filters pet in order to delete
- [ ] redirect to main page - route push
