### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by JohannMerck** [Inelukas/pet-app#56]
## Value proposition

As a user,
I want to have clear instructions for the main functions of the Pet Care App,
so that I can understand and use the app's most important features effectively.

## Description
Instructions are implemented on the Starting Page of the App, presenting a clear overview and explanation of all Features of the App. Additionally, specific functions and effects are explained on the corresponding pages, for example the consequences of choosing particular characteristics on the Details page for the Pets Values.   

## Acceptance criteria

- [ ] a show Instructions button is implemented on the Start Page 
- [ ] clicking the button opens an instructions component, explaining all main features of the game, which are: 
   - [ ] Garden Page
   - [ ] Pet List
   - [ ] Pet Details 
   - [ ] Create Pet 
   - [ ] Graveyard
   - [ ] Mini-Games
   - [ ] Achievements 

## Tasks

- [ ] create feature branch instructions
- [ ] Implement toggle instructions button on start page
- [ ] implement instrcutions regarding the following features: 
   - [ ] Garden Page
   - [ ] Pet List
   - [ ] Pet Details 
   - [ ] Create Pet 
   - [ ] Graveyard
   - [ ] Mini-Games
   - [ ] Achievements

**Comment by JessicaLoers** [comment]
**hello @JohannMerck**  ✌️

Here are some improvements for clarity, consistency, and format. 

### Value proposition
Please revise it according to the format required by us and make the description more precise.
I would suggest revising the phrase "all functions" to "main functions" in the user story. "All functions" can be too broad and may imply that every small feature will be explained in detail, which could overwhelm the user and isn't necessary. 


```code
As a user,
I want to have clear instructions for the main functions of the Pet Care App,
so that I can understand and use the app's most important features effectively.
```

### Acceptance Criteria
Make sure everything is written from the user's perspective, so it's clear what they can expect to see or do. "Toggle" might not be immediately clear to some users.

- A "Show Instructions" button is available on the Start Page.
- When the button is clicked, an instruction is displayed, explaining the main features of the app, including: ....
